### PR TITLE
Ticket 208

### PR DESCRIPTION
**Pull request by philion**
Changes to address ticket http://10.10.0.218/issues/208

* Added more robust check and fallback for email body.
* Added HTML stripping for HTML emails.
* Added removal of google footer.
* Added check for "On ... wrote:" forward marker.
* Added test cases to test all of the above.

### CODE REVIEW

**Review by infrared0 — CHANGES_REQUESTED** [review]
wondering if since this is a public repo, we could scrub my personal email and phone number from the test cases? after that I am all good to merge changes!

**Comment by philion** [comment]
I have run a series of find and replace to remove anything referencing infrared or Esther, and added the updated tests.

**Review by infrared0 — APPROVED** [review]
Looks great!

**Comment by infrared0** [comment]
I believe you can merge the changes now?

**Pull request merged**
